### ISSUE TITLE
Crash With Mekanism (Happy First Issue!)

### ISSUE THREAD

**Issue by Stryder914MC** [jedijoe93/ImmortuosCalyx#1]
All jokes aside, let's get into the meat and bones. It occurs whenever I attempt to join a world.  It worked fine before I installed Mekanism.
Also, really enjoy this mod. I'm planning to use it in a sort of post-apocalyptic sci-fi horror modpack.

---- Minecraft Crash Report ----
// My bad.

Time: 10/10/20 10:36 PM
Description: Ticking entity

java.lang.ClassCastException: com.jedijoe.ImmortuosCalyx.Infection.InfectionManager cannot be cast to top.theillusivec4.curios.api.type.capability.ICuriosItemHandler
	at top.theillusivec4.curios.common.event.CuriosEventHandler$$Lambda$8718/1593276958.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.tick(CuriosEventHandler.java:351) ~[?:property(class java.lang.String, map(provider(?)))] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_190_CuriosEventHandler_tick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:204) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$8712/1360865747.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$8382/1329082422.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at top.theillusivec4.curios.common.event.CuriosEventHandler$$Lambda$8718/1593276958.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.tick(CuriosEventHandler.java:351) ~[?:property(class java.lang.String, map(provider(?)))] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_190_CuriosEventHandler_tick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:204) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$8712/1360865747.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:drowned (net.minecraft.entity.monster.DrownedEntity)
	Entity ID: 16
	Entity Name: Drowned
	Entity's Exact location: -184.50, 49.00, 83.50
	Entity's Block location: World: (-185,49,83), Chunk: (at 7,3,3 in -12,5; contains blocks -192,0,80 to -177,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,74,144), Chunk: (at 0,4,0 in -14,9; contains blocks -224,0,144 to -209,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1 game time, 1 day time
	Level name: New Worldvcxzb
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 56173 (now: false), thunder time: 82225 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$8382/1329082422.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2333021056 bytes (2224 MB) / 3690987520 bytes (3520 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.12.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.12
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.12-client.jar Minecraft {minecraft@1.16.3 DONE}
		Mekanism-1.16.3-10.0.11.436.jar Mekanism {mekanism@10.0.11 DONE}
		forge-1.16.3-34.1.12-universal.jar Forge {forge@34.1.12 DONE}
		pneumaticcraft-repressurized-1.16.3-2.4.2-49.jar PneumaticCraft: Repressurized {pneumaticcraft@1.16.3-2.4.2-49 DONE}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 DONE}
		BiomesOPlenty-1.16.3-12.0.0.405-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.405 DONE}
		MekanismTools-1.16.3-10.0.11.436.jar Mekanism: Tools {mekanismtools@10.0.11 DONE}
		MekanismAdditions-1.16.3-10.0.11.436.jar Mekanism: Additions {mekanismadditions@10.0.11 DONE}
		BetterCaves-1.16.2-1.0.3.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.3 DONE}
		immortuoscalyx-1.1.jar Immortuos Calyx {immortuoscalyx@1.1 DONE}
		MekanismGenerators-1.16.3-10.0.11.436.jar Mekanism: Generators {mekanismgenerators@10.0.11 DONE}
	Crash Report UUID: b9f76c1f-ae7c-4a58-a0cb-8990ef6d7ef7
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:mekanism, mod:forge, mod:pneumaticcraft, mod:curios, mod:biomesoplenty (incompatible), mod:mekanismtools, mod:mekanismadditions, mod:bettercaves (incompatible), mod:immortuoscalyx, mod:mekanismgenerators
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13476 Compatibility Profile Context 22.19.180.1536
	OpenGlRenderer: AMD Radeon R7 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Stryder914MC** [comment]
Wait, I think I posted the wrong crash report. Hold on...

**Comment by Stryder914MC** [comment]
Here's a reproduction of the actual crash, without Curios.
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 10/10/20 10:51 PM
Description: Ticking entity

java.lang.ClassCastException: com.jedijoe.ImmortuosCalyx.Infection.InfectionManager cannot be cast to mekanism.common.lib.radiation.capability.IRadiationEntity
	at mekanism.common.lib.radiation.RadiationManager$$Lambda$8671/611924888.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at mekanism.common.lib.radiation.RadiationManager.updateEntityRadiation(RadiationManager.java:232) ~[?:10.0.11] {re:classloading}
	at mekanism.common.lib.radiation.RadiationManager.onLivingUpdate(RadiationManager.java:307) ~[?:10.0.11] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_158_RadiationManager_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:204) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$8638/985874868.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$8321/1996939010.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mekanism.common.lib.radiation.RadiationManager$$Lambda$8671/611924888.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at mekanism.common.lib.radiation.RadiationManager.updateEntityRadiation(RadiationManager.java:232) ~[?:10.0.11] {re:classloading}
	at mekanism.common.lib.radiation.RadiationManager.onLivingUpdate(RadiationManager.java:307) ~[?:10.0.11] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_158_RadiationManager_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:310) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:204) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$8638/985874868.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:drowned (net.minecraft.entity.monster.DrownedEntity)
	Entity ID: 25
	Entity Name: Drowned
	Entity's Exact location: -149.50, 49.00, 49.50
	Entity's Block location: World: (-150,49,49), Chunk: (at 10,3,1 in -10,3; contains blocks -160,0,48 to -145,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading}


-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2094
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,74,144), Chunk: (at 0,4,0 in -14,9; contains blocks -224,0,144 to -209,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2 game time, 2 day time
	Level name: New Worldvcxzb
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 56172 (now: false), thunder time: 82224 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$8321/1996939010.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3049477600 bytes (2908 MB) / 4294967296 bytes (4096 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.12.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.12.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.12
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.12-client.jar Minecraft {minecraft@1.16.3 DONE}
		Mekanism-1.16.3-10.0.11.436.jar Mekanism {mekanism@10.0.11 DONE}
		forge-1.16.3-34.1.12-universal.jar Forge {forge@34.1.12 DONE}
		pneumaticcraft-repressurized-1.16.3-2.4.2-49.jar PneumaticCraft: Repressurized {pneumaticcraft@1.16.3-2.4.2-49 DONE}
		BiomesOPlenty-1.16.3-12.0.0.405-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.405 DONE}
		MekanismTools-1.16.3-10.0.11.436.jar Mekanism: Tools {mekanismtools@10.0.11 DONE}
		MekanismAdditions-1.16.3-10.0.11.436.jar Mekanism: Additions {mekanismadditions@10.0.11 DONE}
		BetterCaves-1.16.2-1.0.3.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.3 DONE}
		immortuoscalyx-1.1.jar Immortuos Calyx {immortuoscalyx@1.1 DONE}
		MekanismGenerators-1.16.3-10.0.11.436.jar Mekanism: Generators {mekanismgenerators@10.0.11 DONE}
	Crash Report UUID: 7a359ece-e844-4e89-a731-2bd83cca7451
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:mekanism, mod:forge, mod:pneumaticcraft, mod:biomesoplenty (incompatible), mod:mekanismtools, mod:mekanismadditions, mod:bettercaves (incompatible), mod:immortuoscalyx, mod:mekanismgenerators
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13476 Compatibility Profile Context 22.19.180.1536
	OpenGlRenderer: AMD Radeon R7 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by jedijoe93** [comment]
I've identified the issue, and am working on a fix

**Comment by jedijoe93** [comment]
The issue has been patched locally, and a fix will be up alongside some other changes in the next update, probably within the next few hours. Thank you again, and apologies for the wait!

**Comment by Stryder914MC** [comment]
Ah, you're a lifesaver, man! Thank you!
